.PHONY: install run dev clean

# Install dependencies using uv
install:
	uv sync

# Run the standard scraper CLI
run:
	uv run --active main.py

# Run the FastAPI server (if running API endpoints via uvicorn)
run-api:
	uv run uvicorn main:app --reload

# Clean generated bytecode and temporary cache files
clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete